version: '2'
services:
  oddb:
    image: "mariadb"
    container_name: "oddb"
    environment:
    - "MYSQL_ROOT_PASSWORD=pass123"
  od:
    container_name: "od"
    image: "aksaramaya/openedoo:unstable"
    ports:
    - "5000:5000"
    volumes:
    - .:/opt/od
    links:
    - "oddb:oddb"
